# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='surname',
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
