# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 20:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fisiorganizer_SITE', '0002_auto_20170704_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
                ('id_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.Exercise')),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructot', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
