# Generated by Django 5.1 on 2024-08-30 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0002_auto_20170721_0036'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField()),
                ('details', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='exerciseequipment',
            name='id_equipment',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='id_level',
        ),
        migrations.RemoveField(
            model_name='exerciseequipment',
            name='id_exercise',
        ),
        migrations.RemoveField(
            model_name='sessionexercise',
            name='id_exercise',
        ),
        migrations.RemoveField(
            model_name='exercisefocus',
            name='id_exercise',
        ),
        migrations.RemoveField(
            model_name='exercisefocus',
            name='id_focus',
        ),
        migrations.RemoveField(
            model_name='sessionexercise',
            name='id_session',
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description_before', models.TextField(max_length=500)),
                ('description_after', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.customer')),
                ('id_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.place')),
            ],
        ),
        migrations.DeleteModel(
            name='Equipment',
        ),
        migrations.DeleteModel(
            name='ExerciseEquipment',
        ),
        migrations.DeleteModel(
            name='Exercise',
        ),
        migrations.DeleteModel(
            name='ExerciseFocus',
        ),
        migrations.DeleteModel(
            name='Focus',
        ),
        migrations.DeleteModel(
            name='SessionExercise',
        ),
    ]
