# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-27 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0002_auto_20170721_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionexercise',
            name='alias',
        ),
    ]
