# Generated by Django 4.2.1 on 2025-05-09 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0003_remove_sessionexercise_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingEntryType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Evolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('evolution_text', models.TextField(max_length=500)),
                ('id_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.customer')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingEntryCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.accountingentrytype')),
            ],
        ),
        migrations.CreateModel(
            name='AccountingEntry',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=500)),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.accountingentrycategory')),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.accountingentrytype')),
            ],
        ),
    ]
