# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-04 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0003_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=25)),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
                ('cellphone', models.PositiveIntegerField(blank=True, null=True)),
                ('CEP', models.PositiveIntegerField(blank=True, null=True)),
                ('age', models.IntegerField()),
                ('details', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_extra',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='user_extra',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user_extra',
            name='cellphone',
        ),
        migrations.RemoveField(
            model_name='user_extra',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_extra',
            name='details',
        ),
        migrations.RemoveField(
            model_name='user_extra',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user_extra',
            name='role',
        ),
        migrations.AlterField(
            model_name='session',
            name='id_customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.Customer'),
        ),
        migrations.AlterField(
            model_name='session',
            name='id_instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
