# Generated by Django 5.1 on 2024-09-02 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0003_place_remove_exerciseequipment_id_equipment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='id_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='evolution',
            old_name='id_instructor',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='evolution',
            old_name='id_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='id_customer',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='id_instructor',
            new_name='instructor',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='id_modality',
            new_name='modality',
        ),
        migrations.RenameField(
            model_name='userextra',
            old_name='id_user',
            new_name='user',
        ),
    ]
