# Generated by Django 5.1 on 2024-09-02 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0004_rename_id_customer_evolution_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evolution',
            name='customer',
        ),
    ]
