# Generated by Django 5.1 on 2024-09-02 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0005_remove_evolution_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolution',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.customer'),
            preserve_default=False,
        ),
    ]
