# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0006_auto_20170705_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=150)),
                ('id_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.Exercise')),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='id_exercise',
        ),
        migrations.AddField(
            model_name='session',
            name='id_train',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.Train'),
            preserve_default=False,
        ),
    ]
