# Generated by Django 5.1 on 2024-09-02 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0006_evolution_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evolution',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.customer'),
        ),
    ]
