# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0007_auto_20170705_1606'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Train',
            new_name='Trainning',
        ),
    ]
