# Generated by Django 5.1 on 2024-09-03 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0007_alter_evolution_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Patient',
        ),
    ]
