# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 16:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Fisiorganizer_SITE', '0008_auto_20170705_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suplemento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
