# Generated by Django 5.1.1 on 2024-09-04 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0008_rename_customer_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolution',
            old_name='customer',
            new_name='patient',
        ),
    ]
