# Generated by Django 5.1.1 on 2024-09-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0009_rename_customer_evolution_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AddField(
            model_name='patient',
            name='born_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
