# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-05 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0009_suplemento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suplemento',
            name='id_user',
        ),
        migrations.DeleteModel(
            name='Suplemento',
        ),
    ]
