# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-10 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0010_auto_20170705_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionExercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=150)),
            ],
        ),
        migrations.RenameModel(
            old_name='User_extra',
            new_name='UserExtra',
        ),
        migrations.RemoveField(
            model_name='trainning',
            name='id_exercise',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='session',
            name='id_train',
        ),
        migrations.AddField(
            model_name='exercise',
            name='reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cellphone',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Trainning',
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='id_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.Exercise'),
        ),
        migrations.AddField(
            model_name='sessionexercise',
            name='id_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.Session'),
        ),
    ]
