# Generated by Django 5.1.1 on 2024-09-06 13:54

import Fisiorganizer_SITE.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0011_alter_place_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='born_date',
        ),
        migrations.AddField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='cellphone',
            field=models.CharField(max_length=13, validators=[Fisiorganizer_SITE.validators.validate_phone]),
        ),
    ]
