# Generated by Django 5.1.1 on 2024-09-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0012_remove_patient_born_date_patient_birthday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birthday',
            new_name='birth_day',
        ),
    ]
