# Generated by Django 5.1.1 on 2024-09-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0013_rename_birthday_patient_birth_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='birth_day',
            new_name='birthday',
        ),
    ]
