# Generated by Django 5.1.1 on 2024-09-10 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0014_rename_birth_day_patient_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='session',
            name='type',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.type'),
            preserve_default=False,
        ),
    ]
