# Generated by Django 5.1.1 on 2024-09-10 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0015_type_delete_level_alter_patient_birthday_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Service',
        ),
        migrations.RemoveField(
            model_name='session',
            name='type',
        ),
    ]
