# Generated by Django 5.1.1 on 2024-09-10 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fisiorganizer_SITE', '0016_rename_type_service_remove_session_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='Service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Fisiorganizer_SITE.service'),
            preserve_default=False,
        ),
    ]
